2022-02-01 18:57:35,229 ERROR: Exception on / [GET] [in /Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/rossroberts/repositories/MediaTracker/app/routes.py", line 56, in index
    return render_template('index.html', title='Home Page', form=form, post=posts)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/rossroberts/repositories/MediaTracker/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/rossroberts/repositories/MediaTracker/app/templates/base.html", line 25, in template
    <form class="navbar-form navbar-left" method="get" action="{{ url_for('main.search'}}">
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
2022-02-01 18:58:12,472 INFO: MediaTracker Startup [in /Users/rossroberts/repositories/MediaTracker/app/__init__.py:49]
2022-02-01 18:58:15,072 ERROR: Exception on / [GET] [in /Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/rossroberts/repositories/MediaTracker/app/routes.py", line 56, in index
    return render_template('index.html', title='Home Page', form=form, post=posts)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/rossroberts/repositories/MediaTracker/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/rossroberts/repositories/MediaTracker/app/templates/base.html", line 64, in template
    {% endfpr %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endfpr'. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.
2022-02-01 18:58:36,837 INFO: MediaTracker Startup [in /Users/rossroberts/repositories/MediaTracker/app/__init__.py:49]
2022-02-01 18:58:37,796 ERROR: Exception on / [GET] [in /Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/rossroberts/repositories/MediaTracker/app/routes.py", line 56, in index
    return render_template('index.html', title='Home Page', form=form, post=posts)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/rossroberts/repositories/MediaTracker/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/rossroberts/repositories/MediaTracker/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block 'body'
    {% block navbar %}
  File "/Users/rossroberts/repositories/MediaTracker/app/templates/base.html", line 17, in block 'navbar'
    <a class="navbar-brand" href="{{ url_for('main.index') }}">MediaTracker</a>
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/werkzeug/routing.py", line 2314, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.index'. Did you mean 'index' instead?
2022-02-01 19:00:48,426 INFO: MediaTracker Startup [in /Users/rossroberts/repositories/MediaTracker/app/__init__.py:49]
