2022-01-29 13:52:40,745 INFO: MediaTracker Startup [in /Users/rossroberts/repositories/MediaTracker/app/__init__.py:45]
2022-01-29 14:01:18,446 INFO: MediaTracker Startup [in /Users/rossroberts/repositories/MediaTracker/app/__init__.py:45]
2022-01-29 14:01:20,822 INFO: MediaTracker Startup [in /Users/rossroberts/repositories/MediaTracker/app/__init__.py:45]
2022-01-29 14:01:31,432 INFO: MediaTracker Startup [in /Users/rossroberts/repositories/MediaTracker/app/__init__.py:45]
2022-01-31 17:33:11,645 INFO: MediaTracker Startup [in /Users/rossroberts/repositories/MediaTracker/app/__init__.py:45]
2022-01-31 17:34:15,116 ERROR: Exception on /index [GET] [in /Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/rossroberts/repositories/MediaTracker/app/routes.py", line 22, in index
    return render_template('index.html', title='Home')
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/rossroberts/repositories/MediaTracker/app/templates/index.html", line 6, in template
    {{% form.hidden_tag() }}
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
2022-01-31 17:37:57,202 INFO: MediaTracker Startup [in /Users/rossroberts/repositories/MediaTracker/app/__init__.py:45]
2022-01-31 17:37:58,756 ERROR: Exception on / [GET] [in /Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/rossroberts/repositories/MediaTracker/app/routes.py", line 22, in index
    return render_template('index.html', title='Home')
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/rossroberts/repositories/MediaTracker/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/rossroberts/repositories/MediaTracker/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/rossroberts/repositories/MediaTracker/app/templates/index.html", line 6, in block 'content'
    {{ form.hidden_tag() }}
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/jinja2/environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2022-01-31 17:42:06,994 INFO: MediaTracker Startup [in /Users/rossroberts/repositories/MediaTracker/app/__init__.py:45]
2022-01-31 17:42:08,651 ERROR: Exception on / [GET] [in /Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/rossroberts/repositories/MediaTracker/app/routes.py", line 22, in index
    return render_template('index.html', title='Home')
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/rossroberts/repositories/MediaTracker/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/rossroberts/repositories/MediaTracker/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/rossroberts/repositories/MediaTracker/app/templates/index.html", line 6, in block 'content'
    {{ form.hidden_tag() }}
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/jinja2/environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
